# https://taskfile.dev

version: "3"

vars:
  BIN: twl

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o {{.BIN}} main.go
    silent: true

  install:
    desc: Install binary in macos
    deps:
      - build
    cmds:
      - sudo cp {{.BIN}} /usr/local/bin/{{.BIN}}
    silent: true
