# https://taskfile.dev

version: "3"

vars:
  BIN: twl
  DIST: dist

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o {{.DIST}}/{{.BIN}} main/main.go
    silent: true

  run:
    desc: Build the project
    cmds:
      - go run main/main.go
    silent: true

  install:
    desc: Install binary in macos
    deps:
      - build
    cmds:
      - sudo cp {{.DIST}}/{{.BIN}} /usr/local/bin/{{.BIN}}
    silent: true
